# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NAVI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('url', models.URLField(verbose_name='\u7f51\u5740')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u63cf\u8ff0')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'db_table': 'navi',
                'verbose_name': '\u7ad9\u70b9\u5bfc\u822a',
                'verbose_name_plural': '\u7ad9\u70b9\u5bfc\u822a',
                'permissions': (('can_add_navi', '\u6dfb\u52a0\u7ad9\u70b9'), ('can_change_navi', '\u4fee\u6539\u7ad9\u70b9'), ('can_delete_navi', '\u5220\u9664\u7ad9\u70b9'), ('can_view_navi', '\u67e5\u770b\u7ad9\u70b9')),
            },
        ),
    ]
