# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('assetsgroup', models.ManyToManyField(to='assets.AssetGroups', verbose_name='\u8d44\u4ea7\u7ec4')),
                ('group', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='\u7528\u6237\u7ec4')),
                ('perm', models.ManyToManyField(to='auth.Permission', verbose_name='\u6743\u9650')),
            ],
            options={
                'db_table': 'asset_permission',
                'verbose_name': '\u6743\u9650\u4fe1\u606f',
                'verbose_name_plural': '\u6743\u9650\u4fe1\u606f',
                'permissions': (('can_add_asset_permission', '\u6dfb\u52a0\u8d44\u4ea7\u7ec4\u6743\u9650'), ('can_change_asset_permission', '\u4fee\u6539\u8d44\u4ea7\u7ec4\u6743\u9650'), ('can_delete_asset_permission', '\u5220\u9664\u8d44\u4ea7\u7ec4\u6743\u9650'), ('can_view_asset_permission', '\u67e5\u770b\u8d44\u4ea7\u7ec4\u6743\u9650')),
            },
        ),
    ]
