# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetpermission',
            name='perm',
        ),
        migrations.AddField(
            model_name='assetpermission',
            name='memo',
            field=models.TextField(blank=True, verbose_name='\u5907\u6ce8\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='assetpermission',
            name='group',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='asset_permissions', to='auth.Group', verbose_name='\u7528\u6237\u7ec4'),
        ),
    ]
