# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetGroups',
            new_name='AssetGroup',
        ),
        migrations.AlterModelTable(
            name='assetgroup',
            table='assetgroup',
        ),
    ]
