# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.URLField(verbose_name='\u57df\u540d\u540d\u79f0')),
                ('ip', models.GenericIPAddressField(verbose_name='\u89e3\u6790IP')),
                ('env', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4f7f\u7528\u73af\u5883')),
                ('add_area', models.CharField(blank=True, choices=[(b'1', 'dnspod'), (b'2', 'company-dns'), (b'3', 'azure-dnsmasq')], max_length=30, null=True, verbose_name='\u6dfb\u52a0\u4f4d\u7f6e')),
                ('usage', models.CharField(max_length=50, verbose_name='\u7528\u9014')),
                ('applicant', models.CharField(max_length=50, verbose_name='\u7533\u8bf7\u4eba')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('expiration_time', models.DateTimeField(blank=True, max_length=200, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
            ],
            options={
                'db_table': 'domain',
                'verbose_name': '\u57df\u540d\u7ba1\u7406',
                'verbose_name_plural': '\u57df\u540d\u7ba1\u7406',
                'permissions': (('can_add_domain', '\u6dfb\u52a0\u57df\u540d'), ('can_change_domain', '\u4fee\u6539\u57df\u540d'), ('can_delete_domain', '\u5220\u9664\u57df\u540d'), ('can_view_domain', '\u67e5\u770b\u57df\u540d')),
            },
        ),
    ]
